[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@bisonai/orakl-contracts/=lib/orakl/contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

ffi = true
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

optimizer = true
optimizer_runs = 200

[rpc_endpoints]
kaia_kairos = "${KAIROS_RPC_URL}"
kaia_mainnet = "${MAINNET_RPC_URL}"